.PHONY: clean All

All:
	@echo "----------Building project:[ DS - Debug ]----------"
	@cd "DS" && "$(MAKE)" -f  "DS.mk"
clean:
	@echo "----------Cleaning project:[ DS - Debug ]----------"
	@cd "DS" && "$(MAKE)" -f  "DS.mk" clean
